"""Changes for  alembic

Revision ID: 4af663c9411b
Revises: 
Create Date: 2025-06-22 10:34:09.378846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4af663c9411b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('document_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='document_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_filename'), 'document', ['filename'], unique=True)
    op.create_table('documents_text',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], name=op.f('documents_text_doc_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('documents_text_pkey'))
                    )
    op.create_index(op.f('ix_documents_text_id'), 'documents_text', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_text_id'), table_name='documents_text')
    op.drop_table('documents_text')
    op.drop_index(op.f('ix_document_filename'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
