"""empty message

Revision ID: 467e55bf4faf
Revises: 8d2151fdef46
Create Date: 2025-07-03 19:04:51.417941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467e55bf4faf'
down_revision: Union[str, Sequence[str], None] = '8d2151fdef46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_filename'), table_name='document')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index(op.f('ix_document_filename'), 'document', ['filename'], unique=True)
    # ### end Alembic commands ###
