# Generated by Django 5.2.3 on 2025-06-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='size',
            field=models.FloatField(blank=True, help_text='Размер файла в КБ', null=True),
        ),
    ]
