# Generated by Django 5.2.3 on 2025-07-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usertodocs_delete_usertodoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='external_doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
